### ISSUE TITLE
when we place jenkins logo on jenkins pod, its not loading 

### ISSUE THREAD

**Issue by DeekshithSN** [jenkinsci/simple-theme-plugin#154] opened 2023-08-14 11:40 UTC
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```
Jenkins
  ```

</details>

we have installed jenkins via Kubernetes pod, we are trying to change logo.

When we place our logo in <Jenkins_home>/userContent/layout/logo.png and under configure system when we add custom css as below the logo never load 

```
.logo img {
content: url("<Jenkins_home>/userContent/layout/logo.png");
}
```

### What Operating System are you using (both controller, and any agents involved in the problem)?

we use Kubernetes pod, image that we use is  **jenkins/jenkins:2.387.2**

### Reproduction steps

1. place the logo in pod location <Jenkins_home>/userContent/layout/
2. in configure system --> under theme section --> extra css --> provide below css 

```
.logo img {
content: url("<Jenkins_home>/userContent/layout/logo.png");
}
```

### Expected Results

logo should be displayed on jenkins home page 

### Actual Results

logo / image does not load

**Comment by TobiX** [comment] 2023-08-15 16:51
Maybe try using the [Customizable Header](https://plugins.jenkins.io/customizable-header/) plugin instead?

Otherwise: Works for me. Be aware that your selector matches both, the Jenkins logo and the text right of the logo, you might want to use `#jenkins-head-icon` to target only the icon.

**Comment by TobiX** [comment] 2023-09-11 13:00
Closing since not reproducible. Please provide more information if you think this issue still exists.

**Closed by TobiX** 2023-09-11 13:00 UTC
Labels: question
