### ISSUE TITLE
Theme not showing up at Manage Jenkins > System

### ISSUE THREAD

**Issue by aFlavius04** [jenkinsci/simple-theme-plugin#209] opened 2024-07-25 12:12 UTC
### Jenkins and plugins versions report

println("Jenkins: ${Jenkins.instance.getVersion()}")
println("OS: ${System.getProperty('os.name')} - ${System.getProperty('os.version')}")
println("Java: ${System.getProperty('java.version')} - ${System.getProperty('java.vm.vendor')} (${System.getProperty('java.vm.name')})")
println "---"

Jenkins.instance.pluginManager.plugins
  .collect()
  .sort { it.getShortName() }
  .each {
    plugin -> println("${plugin.getShortName()}:${plugin.getVersion()}")
  }
return

### What Operating System are you using (both controller, and any agents involved in the problem)?

Windows 10 for the browser in which the jenkins is opened

### Reproduction steps

1. Installed Simple Theme 
2. Went to Manage Jenkins > System 
3. Theme missing

### Expected Results

Manage Jenkins > System > Theme

### Actual Results

Manage Jenkins > System
Theme was missing

**Comment by TobiX** [comment] 2024-07-26 08:24
Duplicate of #204. tldr: There is now an "appearance" section in the Jenkins configuration

**Closed by TobiX** 2024-07-26 08:24 UTC
Labels: duplicate, invalid
